### test
GET http://localhost:5000
Content-Type: application/json

### get all
GET http://localhost:5000/restaurant
Content-Type: application/json

### create
POST http://localhost:5000/restaurant
Content-Type: application/json

{
    "name": "res 2",
    "address": "res 2 add",
    "vegOnly": false,
    "cost": "350",
    "cuisineTypes": ["indian", "thai"],
    "isOpen": true
}

### get single
GET http://localhost:5000/restaurant/fed03f78-744d-47c0-bb14-60ca52b475e7
Content-Type: application/json

### update single
PATCH http://localhost:5000/restaurant/
Content-Type: application/json

{
    "address": "res 1 address"
}

### delete single
DELETE  http://localhost:5000/restaurant/
Content-Type: application/json
