### test
GET http://localhost:5000
Content-Type: application/json

### get all
GET http://localhost:5000/restaurant
Content-Type: application/json

### get all with filter
# cuisineTypes - for OR condition use "|" and for AND condition use "," => this url concatenation can be handled in frontend, as an indication to parse in the backend
# AND
GET http://localhost:5000/restaurant?cost=low&vegOnly=true&cuisineTypes=italian
Content-Type: application/json
# OR
GET http://localhost:5000/restaurant?cost=low&vegOnly=true&cuisineTypes=italian|indian
Content-Type: application/json

### create
POST http://localhost:5000/restaurant
Content-Type: application/json

{
    "name": "res 3",
    "address": "res 3 add",
    "vegOnly": false,
    "cost": "600",
    "cuisineTypes": ["spanish", "morrocon"],
    "isOpen": true
}

### get single
GET http://localhost:5000/restaurant/408f8194-4d49-4c48-864c-30969ce28b57
Content-Type: application/json

### update single
PATCH http://localhost:5000/restaurant/408f8194-4d49-4c48-864c-30969ce28b57
Content-Type: application/json

{
    "address": "res 1 address"
}

### delete single
DELETE  http://localhost:5000/restaurant/408f8194-4d49-4c48-864c-30969ce28b57
Content-Type: application/json
